### PR TITLE
feat: add class test functionality

### LINKED ISSUE #86: Class Test Papers
- Add support to upload class test papers
- Rest is self explanatory
- Just need to add "ct" option to the "exam" field

### PR DESCRIPTION
**Pull request by Majestic9169**
# Description

- add 'ct' to Exam type in question_paper.ts
- modify the searchForm component to add the classtest option
- modify the PaperEditModal to be able to set a paper as a classtest
- edit util validateInput to recognise 'ct'

Fixes #86 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Has This Been Tested?

- just checked the relevant modals/radio options on localhost

# Checklist:

- [x] My code follows the style guidelines of this project
  - the search form has "End/Mid Sem" as the default option, should "/Class Test" also be included?
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Majestic9169** [comment]
no changes to backend yet

**Comment by harshkhandeparkar** [comment]
@Majestic9169 can you rebase this pr?

**Comment by Majestic9169** [comment]
rebasing means update the fork with the commits that happened after I opened the pr right?
so basically 
1. ```git fetch upstream```
2. ```git rebase upstream/main```
right?

doing this threw some merge conflicts, so I'm not sure if this is what I'm supposed to do

**Comment by harshkhandeparkar** [comment]
> rebasing means update the fork with the commits that happened after I opened the pr right? so basically
> 
>     1. `git fetch upstream`
> 
>     2. `git rebase upstream/main`
>        right?
> 
> 
> doing this threw some merge conflicts, so I'm not sure if this is what I'm supposed to do

It will throw merge conflicts. You will have to resolve them and `git push --force-with-lease`. It takes some experience to get it right. Also, the PR itself should not have any merge conflicts.

**Comment by Majestic9169** [comment]
i rebased and force pushed, but the vercel deployment check failed :(

could you confirm where I messed up, I don't think I can see the vercel error

**Comment by harshkhandeparkar** [comment]
Changes have already been committed to main :) Sorry but closing this.

**Pull request closed without merging**
