### PR TITLE
MetaKGP

### PR DESCRIPTION
**Pull request by shikharish**

### CODE REVIEW

**Comment by chirag-ghosh** [comment]
I see no problem with the current implementation

**Comment by shikharish** [comment]
I believe "MetaKGP" is more appropriate. It brings greater clarity and recognition to the acronym, especially given its association with Kharagpur and IIT Kharagpur. We should stick to one convention and follow it. The MetaKGP logo follows this convention.

**Comment by rajivharlalka** [comment]
> I believe "MetaKGP" is more appropriate. It brings greater clarity and recognition to the acronym, especially given its association with Kharagpur and IIT Kharagpur. We should stick to one convention and follow it. The MetaKGP logo follows this  convention. 

image

**Comment by chirag-ghosh** [comment]
"Metakgp", "metakgp", "metaKGP", "MetaKGP" are all the same and refer to the same thing. The abbreviation of Kharagpur as KGP is of such a common usage in the IIT Kharagpur community that I don't think any such highlight is necessary. I do not think any particular version is more appropriate and people are free to use any version they want. Therefore, I don't think this needs to be explicitly changed.

P.S. Metakgp logo has "metaKGP" with a small 'm'. Your change does not account for that.

**Comment by shikharish** [comment]
There are multiple instances of both.
image

"Metakgp" shows no significance or relation to IIT KGP. Someone can read it as _Metak-gp_. "MetaKGP" shows that the KGP means something it has relation to.

**Comment by chirag-ghosh** [comment]
You just proved the point that there are multiple instances of the same thing. The best way to solve this issue is to ask  the founders and senior members regarding their initial thoughts regarding it. Please bring up this issue in the slack general channel. I personally feel this to be not the best use of everyone's time though.

**Comment by shikharish** [comment]
Closing this for now. Will bring it up on slack later.

**Pull request closed without merging**
